services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: postgres_local
    environment:
      POSTGRES_DB: ${DB_NAME:-data_analysis_local}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-localpassword123}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_data_local:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"  # Map to port 5433 to avoid conflicts with local PostgreSQL
    networks:
      - app-network-local
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-data_analysis_local}"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis_local
    ports:
      - "6380:6379"  # Map to port 6380 to avoid conflicts with local Redis
    networks:
      - app-network-local
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data_local:

networks:
  app-network-local:
    driver: bridge